[tools]
"go" = "1.24.4"
"node" = "22"
"pnpm" = "10"

[tasks.copy-wasm-shim]
alias = ["gojs"]
description = "Copies Go's wasm_exec.js to the public directory"
run = [
	"echo // $(go version) > app/wasm_exec.js",
	"cat $(go env GOROOT)/lib/wasm/wasm_exec.js >> app/wasm_exec.js",
]

[tasks.build-go-wasm]
alias = ["wasm"]
depends = ["copy-wasm-shim"]
description = "Builds the Go WebAssembly module for Tailscale SSH"
env = { GOOS = "js", GOARCH = "wasm" }
run = "go build -o app/hp_ssh.wasm ./cmd/hp_ssh"

[tasks.build-go-agent]
alias = ["agent"]
description = "Builds the Go agent for HostInfo"
run = "go build -o build/hp_agent ./cmd/hp_agent"

[tasks.generate-caddy-certs]
alias = ["mkcert"]
dir = "{{cwd}}/test/caddy/certs"
run = [
	"mkdir -p {{cwd}}/test/caddy/certs",
	"mkcert -install",
	"mkcert localhost"
]

[tasks.ci]
description = "Runs the CI pipeline"
depends = ["build-go-wasm"]
depends_post = ["build-go-agent"]
run = [
	"pnpm install",
	"pnpm run build"
]
